apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-agent
  labels:
    app: rmm-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmm-agent
  template:
    metadata:
      labels:
        app: rmm-agent
    spec:
      containers:
      - name: rmm-agent
        image: ambarbhore1234/rmmagent:rmmagent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
